services:
  crud-api:
    build:
      context: ./crud_api
    environment:
      - API_ALLOW_ORIGINS=${API_ALLOW_ORIGINS}
      - ADMIN_TG_ID=${ADMIN_TG_ID}
      - TG_TOKEN=${TG_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - internal
  tg-mini-app:
    build:
      context: ./tg_mini_app
      args:
        - VITE_CRUD_API_URL=${API_URL}
    depends_on:
      - crud-api
    networks:
      - internal
  nginx:
    hostname: scheduler-nginx
    image: nginx:1.29.8-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - crud-api
      - tg-mini-app
    networks:
      - master-nginx-network
      - internal

networks:
  internal:
  master-nginx-network:
    external: true
