/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as UserBookingRouteImport } from './routes/user/booking'

const AdminIndexLazyRouteImport = createFileRoute('/admin/')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexLazyRoute = AdminIndexLazyRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin/index.lazy').then((d) => d.Route))
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/user/index.lazy').then((d) => d.Route))
const UserBookingRoute = UserBookingRouteImport.update({
  id: '/user/booking',
  path: '/user/booking',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/user/booking.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user/booking': typeof UserBookingRoute
  '/user/': typeof UserIndexRoute
  '/admin/': typeof AdminIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/user/booking': typeof UserBookingRoute
  '/user': typeof UserIndexRoute
  '/admin': typeof AdminIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/user/booking': typeof UserBookingRoute
  '/user/': typeof UserIndexRoute
  '/admin/': typeof AdminIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/user/booking' | '/user/' | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/user/booking' | '/user' | '/admin'
  id: '__root__' | '/' | '/user/booking' | '/user/' | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserBookingRoute: typeof UserBookingRoute
  UserIndexRoute: typeof UserIndexRoute
  AdminIndexLazyRoute: typeof AdminIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/booking': {
      id: '/user/booking'
      path: '/user/booking'
      fullPath: '/user/booking'
      preLoaderRoute: typeof UserBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserBookingRoute: UserBookingRoute,
  UserIndexRoute: UserIndexRoute,
  AdminIndexLazyRoute: AdminIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
