server {
    listen 80;
    server_name crud-scheduler.jeeves-api.tech;

    location / {
        proxy_pass http://crud-api:8000;

        # Information about the original sender
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name tma-scheduler.jeeves-api.tech;

    location / {
        proxy_pass http://tg-mini-app:80;

        # Information about the original sender
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
