"""add service foreign key to appointments

Revision ID: 39d9aaa717aa
Revises: cc0ac54bdeb0
Create Date: 2026-06-11 17:01:12.757934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39d9aaa717aa'
down_revision: Union[str, Sequence[str], None] = 'cc0ac54bdeb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('appointments_service_id_fkey'), 'appointments', 'services', ['service_id'], ['id'])

    conn = op.get_bind()
    conn.execute(sa.text('update appointments set service_id=1 where service_id is null'))

    op.alter_column('appointments', 'service_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('appointments_service_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'service_id')
    # ### end Alembic commands ###
