"""add index on user_id and date to appointments

Revision ID: 4cbd8c3228c0
Revises: ddd4a4d8f0fd
Create Date: 2026-05-06 18:39:23.969995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cbd8c3228c0'
down_revision: Union[str, Sequence[str], None] = 'ddd4a4d8f0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_date', 'appointments', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_date', table_name='appointments')
    # ### end Alembic commands ###
