"""split appointments

Revision ID: 4d66b8baeace
Revises: e0ce84a950e9
Create Date: 2026-05-13 15:59:57.511673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d66b8baeace'
down_revision: Union[str, Sequence[str], None] = 'e0ce84a950e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # https://gist.github.com/paul121/3f36f834725649f9abb7791933ce8d8f

    op.rename_table('appointments', 'blocks')

    new_table = op.create_table('appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id')
    )
    op.create_index(op.f('ix_appointments_user_id'), 'appointments', ['user_id'], unique=False)

    # Request all of the old info.
    conn = op.get_bind()
    res = conn.execute(sa.text('select id, user_id from blocks'))
    results = res.fetchall()

    # Prepare an old_info object to insert into the new table.
    old_info = [{'block_id': r[0], 'user_id': r[1]} for r in results]

    # Insert old_info into new table.
    op.bulk_insert(new_table, old_info)

    op.drop_index(op.f('ix_user_date'), table_name='blocks')
    op.create_unique_constraint('uq_date_time_slot', 'blocks', ['date', 'time_slot_id'])
    op.drop_constraint(op.f('appointments_user_id_fkey'), 'blocks', type_='foreignkey')
    op.drop_column('blocks', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('appointments_user_id_fkey'), 'blocks', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_date_time_slot', 'blocks', type_='unique')
    op.create_index(op.f('ix_user_date'), 'blocks', ['user_id', 'date'], unique=False)

    # Insert new info into old table.
    op.execute(sa.text('update blocks set user_id = appointments.user_id from appointments where blocks.id = appointments.block_id'))
    op.alter_column('blocks', 'user_id', nullable=False)

    op.drop_index(op.f('ix_appointments_user_id'), table_name='appointments')
    op.drop_table('appointments')

    op.rename_table('blocks', 'appointments')
    # ### end Alembic commands ###
