"""add destination template to services

Revision ID: 925104d5d93f
Revises: a1b2c3d4e5f6
Create Date: 2026-06-24 22:03:35.545534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '925104d5d93f'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('destination_template', sa.String(length=256), nullable=True))

    conn = op.get_bind()
    conn.execute(sa.text('update services set destination_template=\'In-person medical consultation. VAT Exempt.\' where destination_template is null'))
    
    op.alter_column('services', 'destination_template', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'destination_template')
    # ### end Alembic commands ###
