"""add invoice id to appointments and cost to services

Revision ID: c17e6ba18ec2
Revises: 39d9aaa717aa
Create Date: 2026-06-16 21:49:45.320379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c17e6ba18ec2'
down_revision: Union[str, Sequence[str], None] = '39d9aaa717aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='appointmentstatus').create(op.get_bind())
    op.add_column('appointments', sa.Column('invoice_id', sa.String(length=256), nullable=True))

    op.add_column('appointments', sa.Column('status', postgresql.ENUM('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='appointmentstatus', create_type=False), nullable=True))
    conn.execute(sa.text('update appointments set status=\'COMPLETED\' where status is null'))
    op.alter_column('appointments', 'status', nullable=False)

    op.alter_column('appointments', 'block_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('appointments_block_id_key'), 'appointments', type_='unique')
    op.drop_constraint(op.f('appointments_block_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_block_id_fkey'), 'appointments', 'blocks', ['block_id'], ['id'], ondelete='SET NULL')

    op.add_column('services', sa.Column('amount_minor', sa.BigInteger(), nullable=True))
    conn.execute(sa.text('update services set amount_minor=0 where amount_minor is null'))
    op.alter_column('services', 'amount_minor', nullable=False)

    op.add_column('services', sa.Column('currency_code', sa.Integer(), nullable=True))
    conn.execute(sa.text('update services set currency_code=980 where currency_code is null'))
    op.alter_column('services', 'currency_code', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'currency_code')
    op.drop_column('services', 'amount_minor')
    op.drop_constraint(op.f('appointments_block_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_block_id_fkey'), 'appointments', 'blocks', ['block_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('appointments_block_id_key'), 'appointments', ['block_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('appointments', 'block_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('appointments', 'status')
    op.drop_column('appointments', 'invoice_id')
    sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='appointmentstatus').drop(op.get_bind())
    # ### end Alembic commands ###
