"""rename slot to start_time in time_slots

Revision ID: e0ce84a950e9
Revises: 4cbd8c3228c0
Create Date: 2026-05-06 21:10:40.244989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0ce84a950e9'
down_revision: Union[str, Sequence[str], None] = '4cbd8c3228c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_slots', 'slot', new_column_name='start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_slots', 'start_time', new_column_name='slot')
    # ### end Alembic commands ###
